spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    store-type: redis
  redis:
    port: 6379
    database: 0
    host: localhost