package hello.controller;

import hello.entity.User;
import hello.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;

/**
 * @author zhaoruipeng
 * @ClassName AuthController
 * @Package hello.controller
 * @date 2018/4/3 15:57
 */
@RestController    // This means that this class is a Controller
public class AuthController extends Base {

    @Autowired // This means to get the bean called userRepository
    private UserRepository userRepository; // Which is auto-generated by Spring, we will use it to handle the data

    @RequestMapping(value = "/login", method = RequestMethod.POST)
    public Object login(@RequestParam(value = "userName", required = true) String userName, @RequestParam(value = "password", required = true) String password) {
//        User user = new User(userName, password);
//        user.setName(userName);
//        user.setEmail(password);
//        System.out.println(userName);
//        System.out.println(password);
//        System.out.println(user.getPassword());
        User user = userRepository.findByName(userName);
        System.out.println(user.getPassword());
        if (User.PASSWORD_ENCODER.matches(password, user.getPassword())) {
            return SUCCESS_JSON;
        }
        return ERROR_JSON;
    }
}
